#!/bin/bash
# Script to generate PNG icons from SVG
# Requires: imagemagick (convert) or inkscape

# Using base64 encoded placeholder icons
# These are simple blue rounded squares with "FK" text

# 16x16
echo 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAWklEQVQ4T2NkoBAwUqifYdQABjT/MzIyMv4H0f///2cEsUEYzgWJgVggMYdRNGBgZPyPkZGRkZGRkZGRkf8PZTAxMDIy/m8EswczAxMDq4HxPwbZg5mBKQbJIMEsAM2YAQBW2QkVjd0vVAAAAABJRU5ErkJggg==' | base64 -d > public/icons/icon-16.png

# 32x32
echo 'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAZ0lEQVRYR+2WwQ6AIAxDN///y3pxGgM0tvua3b1I4kqIuBGJTxLAkRsCJ0igCJIgiiJIgiRwoAU6dAMH6NAMqAKH0EHO4AMf4EsFOEADDjB1A3jADTww9wB4Q/8L4ATvYtMAAAAASUVORK5CYII=' | base64 -d > public/icons/icon-32.png

# 48x48
echo 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAcElEQVRoge3OMQEAAAwCIPw/taJYAszMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMDAAAWq0BU1fF7OAAAAAASUVORK5CYII=' | base64 -d > public/icons/icon-48.png

# 128x128
echo 'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAAjklEQVR4nO3BMQEAAADCoPVP7WsIoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeA24AAABj6UNhgAAAABJRU5ErkJggg==' | base64 -d > public/icons/icon-128.png

echo "Icons generated!"
